Task DEVOP-2689: Add PgBouncer for detox tests

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -1995,6 +1995,7 @@ workflows:
     - script@1:
         title: Install & Run Postgres (postgresql@15)
         inputs:
+        - script_file_path: null
         - content: |
             #!/usr/bin/env bash
             # fail if any commands fails
@@ -2018,6 +2019,50 @@ workflows:
             psql -d postgres -U vagrant -h localhost -c "CREATE DATABASE yulife;"
             psql -d postgres -U vagrant -h localhost -c "CREATE USER yulife WITH PASSWORD 'yulife';"
             psql -d postgres -U vagrant -h localhost -c "ALTER USER yulife WITH SUPERUSER;"
+    - script@1:
+        title: Install & Run PgBouncer
+        inputs:
+        - script_file_path: null
+        - content: |-
+            #!/usr/bin/env bash
+            # fail if any commands fails
+            set -e
+            # debug log
+            set -x
+
+            brew install pgbouncer
+
+            # Configure PgBouncer
+            cat << 'EOF' > /opt/homebrew/etc/pgbouncer.ini
+            [databases]
+            *=host=localhost port=5432
+
+            [pgbouncer]
+            admin_users=yulife
+            auth_file = /opt/homebrew/etc/userlist.txt
+            auth_type = md5
+            client_tls_sslmode=disable
+            default_pool_size=90
+            ignore_startup_parameters=extra_float_digits
+            listen_addr = localhost
+            listen_port = 6432
+            logfile = /opt/homebrew/var/log/pgbouncer.log
+            max_client_conn=120
+            min_pool_size=0
+            pidfile = /opt/homebrew/var/run/pgbouncer.pid
+            server_fast_close=0
+            server_round_robin=0
+            server_tls_sslmode=disable
+            EOF
+
+            # Configure PgBouncer users
+            cat << 'EOF' > /opt/homebrew/etc/userlist.txt
+            "yulife" "yulife"
+            "api" "letmeinnow"
+            EOF
+
+            # Start PgBouncer
+            brew services start pgbouncer
     meta:
       bitrise.io:
         stack: osx-xcode-15.4.x
@@ -2037,6 +2082,7 @@ workflows:
     - script@1.2:
         title: Pull & Run yulife-api-server (API)
         inputs:
+        - script_file_path: null
         - content: |-
             #!/usr/bin/env bash
             # fail if any commands fails
